#!/bin/bash
# 升级后启动服务

MAIN_SCRIPT="/var/apps/dockpit/cmd/main"

if [ -x "$MAIN_SCRIPT" ]; then
    "$MAIN_SCRIPT" start
    exit $?
fi

echo "Error: Main script not found" > "$TRIM_TEMP_LOGFILE"
exit 1
